ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLESPACE TBS_QLSV INCLUDING CONTENTS AND DATAFILES';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLESPACE TBS_QLSV DATAFILE 'tbs_qlsv.dbf' SIZE 50M REUSE AUTOEXTEND ON;

BEGIN
    EXECUTE IMMEDIATE 'DROP PROFILE PRO_BAOMAT CASCADE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE PROFILE PRO_BAOMAT LIMIT 
  FAILED_LOGIN_ATTEMPTS 3 
  PASSWORD_LIFE_TIME 30;

BEGIN
    EXECUTE IMMEDIATE 'DROP ROLE ROLE_GIANGVIEN';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE ROLE ROLE_GIANGVIEN;

BEGIN
    EXECUTE IMMEDIATE 'DROP USER QLSV CASCADE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE USER QLSV IDENTIFIED BY 123 DEFAULT TABLESPACE TBS_QLSV QUOTA UNLIMITED ON TBS_QLSV;

GRANT CONNECT, RESOURCE, DBA TO QLSV;
GRANT UNLIMITED TABLESPACE TO QLSV;
GRANT CREATE PUBLIC SYNONYM TO QLSV;
GRANT DROP PUBLIC SYNONYM TO QLSV;

BEGIN
    EXECUTE IMMEDIATE 'ALTER USER LBACSYS IDENTIFIED BY 123 ACCOUNT UNLOCK';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON LBACSYS.SA_SYSDBA TO QLSV';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON LBACSYS.SA_COMPONENTS TO QLSV';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON LBACSYS.SA_LABEL_ADMIN TO QLSV';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON LBACSYS.SA_POLICY_ADMIN TO QLSV';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON LBACSYS.SA_USER_ADMIN TO QLSV';
    EXECUTE IMMEDIATE 'GRANT EXECUTE ON LBACSYS.CHAR_TO_LABEL TO QLSV';
    EXECUTE IMMEDIATE 'GRANT LBAC_DBA TO QLSV';
EXCEPTION 
    WHEN OTHERS THEN NULL; 
END;
/

SELECT VALUE FROM v$option WHERE PARAMETER = 'Oracle Label Security';

SHOW CON_NAME;