-- 1. Tạo bảng & Dữ liệu
CREATE TABLE SINHVIEN (
    MASV VARCHAR2(20) NOT NULL,
    HOTEN VARCHAR2(100),
    NGAYSINH DATE,
    DIACHI VARCHAR2(500),       
    SODIENTHOAI VARCHAR2(500),  
    DIEM NUMBER(4,2),
    CHUKY VARCHAR2(2000),       
    USERNAME VARCHAR2(30),
    CONSTRAINT PK_SINHVIEN PRIMARY KEY (MASV)
);

CREATE TABLE TAIKHOAN (
    USERNAME VARCHAR2(50) NOT NULL,
    PASSWORD_HASH VARCHAR2(100) NOT NULL, 
    EMAIL VARCHAR2(100),
    CONSTRAINT PK_TAIKHOAN PRIMARY KEY (USERNAME)
);

CREATE TABLE KHOA (
    MAKHOA VARCHAR2(10) NOT NULL,
    TENKHOA VARCHAR2(100),
    DIENTHOAI VARCHAR2(20),
    CONSTRAINT PK_KHOA PRIMARY KEY (MAKHOA)
);

CREATE TABLE LOP (
    MALOP VARCHAR2(10) NOT NULL,
    TENLOP VARCHAR2(100),
    MAKHOA VARCHAR2(10),
    CONSTRAINT PK_LOP PRIMARY KEY (MALOP),
    CONSTRAINT FK_LOP_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
);

CREATE TABLE HOCPHAN (
    MAHP VARCHAR2(10) NOT NULL,
    TENHP VARCHAR2(100),
    SOTINCHI NUMBER(2),
    CONSTRAINT PK_HOCPHAN PRIMARY KEY (MAHP)
);

CREATE TABLE GIANGVIEN (
    MAGV VARCHAR2(10) NOT NULL,
    HOTEN VARCHAR2(100),
    MAKHOA VARCHAR2(10),
    CONSTRAINT PK_GIANGVIEN PRIMARY KEY (MAGV),
    CONSTRAINT FK_GV_KHOA FOREIGN KEY (MAKHOA) REFERENCES KHOA(MAKHOA)
);

INSERT INTO SINHVIEN (MASV, HOTEN, NGAYSINH, DIEM, USERNAME) 
VALUES ('2033230099', 'Le Xuan Hong', TO_DATE('2003-01-01', 'YYYY-MM-DD'), 10, 'QLSV');

INSERT INTO SINHVIEN (MASV, HOTEN, DIEM, USERNAME) 
VALUES ('SV_TEST_02', 'Nguyen Van Test', 9.5, 'QLSV1');

INSERT INTO KHOA (MAKHOA, TENKHOA, DIENTHOAI) VALUES ('CNTT', 'Cong nghe Thong tin', '0283810001');
INSERT INTO KHOA (MAKHOA, TENKHOA, DIENTHOAI) VALUES ('QTKD', 'Quan tri Kinh doanh', '0283810002');
INSERT INTO KHOA (MAKHOA, TENKHOA, DIENTHOAI) VALUES ('DL', 'Du lich', '0283810003');

INSERT INTO LOP (MALOP, TENLOP, MAKHOA) VALUES ('12DHTH', 'Tin hoc 12', 'CNTT');
INSERT INTO LOP (MALOP, TENLOP, MAKHOA) VALUES ('12DHQT', 'Quan tri 12', 'QTKD');
INSERT INTO LOP (MALOP, TENLOP, MAKHOA) VALUES ('13DHTH', 'Tin hoc 13', 'CNTT');

INSERT INTO GIANGVIEN (MAGV, HOTEN, MAKHOA) VALUES ('GV01', 'Nguyen Van A', 'CNTT');
INSERT INTO GIANGVIEN (MAGV, HOTEN, MAKHOA) VALUES ('GV02', 'Tran Thi B', 'QTKD');
INSERT INTO GIANGVIEN (MAGV, HOTEN, MAKHOA) VALUES ('GV03', 'Le Van C', 'CNTT');

INSERT INTO HOCPHAN (MAHP, TENHP, SOTINCHI) VALUES ('BMCSDL', 'Bao mat CSDL', 3);
INSERT INTO HOCPHAN (MAHP, TENHP, SOTINCHI) VALUES ('CTDL', 'Cau truc du lieu', 4);
INSERT INTO HOCPHAN (MAHP, TENHP, SOTINCHI) VALUES ('LTC', 'Lap trinh C#', 3);

COMMIT;

-- 2. Trigger tự động gán User
CREATE OR REPLACE TRIGGER TRG_AUTO_USERNAME
BEFORE INSERT ON SINHVIEN
FOR EACH ROW
BEGIN
  :NEW.USERNAME := SYS_CONTEXT('USERENV', 'SESSION_USER');
END;
/

-- 3. Tạo User con (DAC)
-- Tạo User GIAOVU (Sếp)
BEGIN
   EXECUTE IMMEDIATE 'DROP USER GIAOVU CASCADE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
-- Lưu ý: Sửa thành USERS để tránh lỗi trên máy trường
CREATE USER GIAOVU IDENTIFIED BY 123 DEFAULT TABLESPACE USERS PROFILE PRO_BAOMAT;
GRANT DBA TO GIAOVU;

-- Tạo User SV_TEST
BEGIN EXECUTE IMMEDIATE 'DROP USER SV_TEST CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE USER SV_TEST IDENTIFIED BY 123;
GRANT CREATE SESSION TO SV_TEST;
GRANT SELECT ON SINHVIEN TO SV_TEST;

-- Tạo User QLSV1 (Giảng viên)
BEGIN EXECUTE IMMEDIATE 'DROP USER QLSV1 CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE USER QLSV1 IDENTIFIED BY 123;
GRANT CREATE SESSION TO QLSV1;
GRANT SELECT,DELETE,INSERT,UPDATE ON TAIKHOAN TO QLSV1;
GRANT SELECT,DELETE,INSERT, UPDATE ON SINHVIEN TO QLSV1;

-- Tạo User qlsv2 (Nhân viên)
BEGIN EXECUTE IMMEDIATE 'DROP USER qlsv2 CASCADE'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE USER qlsv2 IDENTIFIED BY 123;
GRANT CREATE SESSION TO qlsv2;
GRANT SELECT ON QLSV.SINHVIEN TO qlsv2;

-- 4. Tạo Synonym & Cấp quyền Public (Quan trọng cho App C#)
CREATE OR REPLACE PUBLIC SYNONYM SINHVIEN FOR QLSV.SINHVIEN;
CREATE OR REPLACE PUBLIC SYNONYM TAIKHOAN FOR QLSV.TAIKHOAN;
GRANT SELECT, INSERT ON TAIKHOAN TO PUBLIC;

-- 5. Chuẩn bị cho Hybrid Encryption & MAC
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SINHVIEN ADD (GHICHU_MAT VARCHAR2(2000), KHOA_GIAIMA VARCHAR2(2000))';
EXCEPTION WHEN OTHERS THEN NULL; 
END;
/
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SINHVIEN ADD (SEC_LEVEL NUMBER DEFAULT 1)';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
COMMIT;

-- 6. Gán nhãn dữ liệu (MAC)
UPDATE SINHVIEN SET SEC_LEVEL = 1; 
UPDATE SINHVIEN SET SEC_LEVEL = 2 WHERE MASV = '2033230099';

DELETE FROM SINHVIEN WHERE MASV = 'SV_TOP_SECRET';
INSERT INTO SINHVIEN (MASV, HOTEN, DIEM, USERNAME, SEC_LEVEL) 
VALUES ('SV_TOP_SECRET', 'Diep Vien 007', 10, 'ADMIN', 3);
COMMIT;

-- 7. Cấu hình VPD (Chính sách bảo mật)
CREATE OR REPLACE FUNCTION POLICY_XEM_DIEM_CANHAN (
  p_schema IN VARCHAR2,
  p_object IN VARCHAR2
) RETURN VARCHAR2 AS
  v_user VARCHAR2(100);
BEGIN
  v_user := SYS_CONTEXT('USERENV', 'SESSION_USER');
  
  IF (v_user = 'GIAOVU' OR v_user = 'QLSV') THEN
      RETURN '1=1'; 
  ELSIF (v_user = 'QLSV1') THEN
      RETURN 'SEC_LEVEL <= 2'; 
  ELSIF (v_user = 'QLSV2') THEN
      RETURN 'SEC_LEVEL = 1'; 
  ELSE
      RETURN 'USERNAME = ''' || v_user || '''';
  END IF;
END;
/

-- Xóa chính sách cũ
BEGIN
  DBMS_RLS.DROP_POLICY(
      object_schema => 'QLSV', 
      object_name   => 'SINHVIEN', 
      policy_name   => 'CHINHSACH_VPD_SV'
  );
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Áp dụng chính sách mới
BEGIN
  DBMS_RLS.ADD_POLICY (
    object_schema    => 'QLSV',
    object_name      => 'SINHVIEN',
    policy_name      => 'CHINHSACH_VPD_SV',
    function_schema  => 'QLSV',
    policy_function  => 'POLICY_XEM_DIEM_CANHAN',
    statement_types  => 'SELECT'
  );
END;
/

-- 8. RBAC (Phân quyền theo Role)
GRANT SELECT ON SINHVIEN TO ROLE_GIANGVIEN;
GRANT SELECT ON TAIKHOAN TO ROLE_GIANGVIEN;
GRANT ROLE_GIANGVIEN TO QLSV1;

-- 9. Audit (Kiểm toán)
AUDIT DELETE ON SINHVIEN BY ACCESS;


SELECT username, 
       timestamp, 
       action_name, 
       obj_name 
FROM USER_AUDIT_TRAIL 
WHERE obj_name = 'SINHVIEN' 
  AND action_name = 'DELETE'
ORDER BY timestamp DESC;

-- FGA Audit
BEGIN
  DBMS_FGA.DROP_POLICY(
    object_schema => 'QLSV',
    object_name   => 'SINHVIEN',
    policy_name   => 'GIAMSAT_SOI_DIEM_CAO'
  );
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
  DBMS_FGA.ADD_POLICY(
    object_schema   => 'QLSV',
    object_name     => 'SINHVIEN',
    policy_name     => 'GIAMSAT_SOI_DIEM_CAO',
    audit_condition => 'DIEM > 9',
    audit_column    => 'DIEM',
    enable          => TRUE,
    statement_types => 'SELECT'
  );
END;
/

SELECT db_user, 
       timestamp, 
       policy_name, 
       sql_text 
FROM DBA_FGA_AUDIT_TRAIL 
WHERE object_name = 'SINHVIEN'
ORDER BY timestamp DESC;

-- 10. Giả lập Hacker tấn công (Sửa điểm của sinh viên chính)
UPDATE SINHVIEN
SET DIEM = '10'
WHERE MASV = 'svtest200';

COMMIT;

-- Kiểm tra kết quả
SELECT * FROM SINHVIEN;